spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: test-client-id   # 필요 시 clientSecret도 추가
  mail:
    password: "local-password"         # 특수문자 있을 수 있으니 따옴표 권장

custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: test-oauth-id
              nickname: test-nickname

  jwt:
    secretKey: "this_is_a_local_secret_key_for_tests_please_change"

mfds:
  easydrug:
    base-url: "http://apis.data.go.kr/1471000/DrbEasyDrugInfoService"
    service-key: "${MFDS_EASYDRUG_SERVICE_KEY:898250dd02c9507e7af8f46f4884556289377200b8117f70b16efc20bc0321b5}"
    timeout-ms: 5000
