server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://guardian-database.c78m4a0okhan.ap-northeast-2.rds.amazonaws.com:3306/guardian_database


custom:
  fileDirPath: /home/ec2-user/app/file

webpush:
  vapid:
    public-key: "${WEB_PUSH_PUBLIC_KEY:}"
    private-key: "${WEB_PUSH_PRIVATE_KEY:}"
    subject: "${WEB_PUSH_SUBJECT:mailto:support@guardian.com}"
  scheduler:
    timezone: "${WEB_PUSH_TIMEZONE:Asia/Seoul}"
