server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/guardian
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  h2:
    console:
      enabled: false
custom:
  fileDirPath: /usr/file

webpush:
  vapid:
    public-key: "BBYI8uB4QjU8uB0SaKnqpEKsqPYV80d5_dmuhzKzzYi8daE8tJi1-cV5SywwzgsgN9Ti5vcbR3uSBkEjy3YvyMo"
    private-key: "Aiwoalc4GXseoWGsOfSSqwDiuFtITXp2kDCSRq1HAWo"
    subject: "mailto:dev@guardian.local"
  scheduler:
    timezone: "Asia/Seoul"
